# Generated by Django 4.2.2 on 2023-09-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="instruction",
            field=models.CharField(max_length=300),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "recipe"), name="unique_ingredient_in_recipe"
            ),
        ),
        migrations.AddConstraint(
            model_name="instruction",
            constraint=models.UniqueConstraint(
                fields=("step_no", "instruction", "recipe"),
                name="unique_instruction_in_recipe",
            ),
        ),
    ]
